### ISSUE TITLE
Player Controller

### ISSUE THREAD

**Issue by BlazingTwist** [BlazingTwist/GDG_Course_Game#1]
Siehe branch [playerController](https://github.com/BlazingTwist/GDG_Course_Game/tree/playerController)

Player Controller mit Funktionen:
- Springen
- Neigungen hoch/runter laufen
- Stufen hoch steigen
- Stehen/bewegen auf beweglichen Plattformen

### TODO (Eric)
- [x] fix: Springen "fühlt sich falsch an"
- [x] Stepheight korrekt implementieren
- [x] Slope max angle implementieren (slope sliding)
- [x] Grundlegender Support für bewegliche Plattformen
